### ISSUE TITLE
Changing config from get_config

### ISSUE THREAD

**Issue by poonehfamili** [gis-ops/pyvalhalla#34]
I am trying to run Valhalla in Python and my code is like this:

from valhalla import Actor, get_config, get_help
import pandas as pd

tile_path = 'C:\\Users\\PFAMILI\\custom_files\\north_east\\valhalla_tiles.tar'
config = get_config(tile_extract=tile_path, verbose=False)

data1_df = pd.DataFrame(...)
df_trip = data1_df[["lon", "lat","type" ]]
lst = df_trip.to_dict('records')

response_text = actor.trace_attributes({"shape":lst, "costing":"auto","shape_match":"walk_or_snap","filters":{"attributes":[],"action":"exclude"}})

I was wondering if I could changing the max path distance for "auto" from get_config( ) or anywhere in this code.

Thank you.

**Comment by poonehfamili** [comment]
I tried this:
response_text = actor.trace_attributes({
    "shape":lst, "costing":"auto","shape_match":"walk_or_snap", 'service_limits': {
         "auto": { "max_distance": 50000000.0, "max_locations": 20, "max_matrix_distance": 400000.0, "max_matrix_location_pairs": 50},
                                        "trace": { 'max_distance': 2000000.0, 'max_gps_accuracy': 100.0, 'max_search_radius': 100.0}
   },
                                        "filters":{"attributes":[],"action":"include"}})
it didn't change the error I am getting for exceed max limit.

**Comment by nilsnolde** [comment]
IMO we have a very explicit example: https://github.com/gis-ops/pyvalhalla?tab=readme-ov-file#usage. just change `config` there and put it at the right spot in that dict. your code snippet doesn't actually create any `Actor`.
