### ISSUE TITLE
3.5.0 Valhalla release

### ISSUE THREAD

**Issue by baileyheading** [gis-ops/pyvalhalla#41]
Could it be a good time for new pyvalhalla version?

As far as I know the only change needed for the python bindings is to support the GDAL option

**Comment by chrstnbwnkl** [comment]
I'm a bit short on time these days, but I can give it a shot when I find a moment. Would indeed be great to bump to 3.5.0

**Comment by baileyheading** [comment]
I build the latest for python quite often manually for various platforms including for supporting geotiff. I previously hacked in a base64 encoder so I could return it into python as part of a json.

**Here is the issue on Valhalla I opened on it:**
https://github.com/valhalla/valhalla/issues/4623

I personally don't think base64 encoded is a terrible option (it was fastest for me to hack into the existing bindings), but returning it as bytes seemed to be preferred option for others in the thread and there are speed/efficiency benefits so it's the logical option probably

**Comment by alisoufali-trendplus** [comment]
Yeah I think the same. It would be very nice if we update the new pyvalhalla version.

**Comment by nilsnolde** [comment]
FWIW, this project is awful to maintain. In its current form. Packaging should become part of upstream Valhalla. This project will be archived.
